$(function(){

    // ADDING TAB
    $('#adduser').click(function(){
      $.ajax({
        url:'adduser.php',
        success:function(data){
          if($("#RSB").is(":hidden"))
          {
            $("#RSB").show(),
            $('.main-chart').html(data)
          }
          else
          {
            $('.main-chart').html(data)
          }
        }
      });
    });

     $('#adddistrib').click(function(){
      $.ajax({
        url:'adddistrib.php',
        success:function(data){
          if($("#RSB").is(":hidden"))
          {
            $("#RSB").show(),
            $('.main-chart').html(data)
          }
          else
          {
            $('.main-chart').html(data)
          }
        }
      });
    });

      $('#addserial').click(function(){
      $.ajax({
        url:'addserial.php',
        success:function(data){
          if($("#RSB").is(":hidden"))
          {
            $("#RSB").show(),
            $('.main-chart').html(data)
          }
          else
          {
            $('.main-chart').html(data)
          }
        }
      });
    });

       $('#addtype').click(function(){
      $.ajax({
        url:'addserialtype.php',
        success:function(data){
          if($("#RSB").is(":hidden"))
          {
            $("#RSB").show(),
            $('.main-chart').html(data)
          }
          else
          {
            $('.main-chart').html(data)
          }
        }
      });
    });

    // END OF ADDING TAB
    $("#CS").click(function(){
     $.ajax({
      url:'currentsubscribe.php',
      success:function(data){
        if($("#RSB").is(":hidden"))
        {
          $('.main-chart').html(data) 
        }
        else
        {
          $('#RSB').hide(),
          $('.main-chart').html(data)
        }
      }
     });
    });

});
